import { promises as fs } from "fs";
import path from "path";

export const QUESTION_UPLOAD_URL = "/uploads/questoes";
export const QUESTION_UPLOAD_DIR = path.join(process.cwd(), "public", "uploads", "questoes");

/** Only accepts paths generated by the upload endpoint; never resolve user input directly. */
export function getQuestionImageFile(image?: string | null) {
  if (!image || !image.startsWith(`${QUESTION_UPLOAD_URL}/`)) return null;
  const filename = path.basename(image);
  if (!/^[a-f0-9-]{36}\.(png|jpe?g|webp)$/i.test(filename)) return null;
  return path.join(QUESTION_UPLOAD_DIR, filename);
}

export function isQuestionImageUrl(image?: string | null) {
  return image === null || image === undefined || Boolean(getQuestionImageFile(image));
}

export async function removeQuestionImage(image?: string | null) {
  const file = getQuestionImageFile(image);
  if (!file) return;
  try {
    await fs.unlink(file);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
}

export async function readQuestionImage(image?: string | null) {
  const file = getQuestionImageFile(image);
  if (!file) return null;
  try {
    return await fs.readFile(file);
  } catch {
    return null;
  }
}
